# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dsl2vql/v1/command.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'dsl2vql/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64sl2vql/v1/command.proto\x12\ndsl2vql.v1\"<\n\x0cQueryCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"\x1f\n\x0fValidateCommand\x12\x0c\n\x04path\x18\x01 \x01(\t\",\n\x0eResolveCommand\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"?\n\x0cPatchCommand\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x11\n\twith_path\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\",\n\x0fGenerateCommand\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03out\x18\x02 \x01(\t\":\n\rRenderCommand\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0b\n\x03out\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"=\n\x0e\x43ompileCommand\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x01\x12\x0e\n\x06height\x18\x03 \x01(\x01\":\n\rExportCommand\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0b\n\x03out\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"\xc1\x03\n\x0b\x44slEnvelope\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12)\n\x05query\x18\n \x01(\x0b\x32\x18.dsl2vql.v1.QueryCommandH\x00\x12/\n\x08validate\x18\x0b \x01(\x0b\x32\x1b.dsl2vql.v1.ValidateCommandH\x00\x12-\n\x07resolve\x18\x0c \x01(\x0b\x32\x1a.dsl2vql.v1.ResolveCommandH\x00\x12)\n\x05patch\x18\r \x01(\x0b\x32\x18.dsl2vql.v1.PatchCommandH\x00\x12/\n\x08generate\x18\x0e \x01(\x0b\x32\x1b.dsl2vql.v1.GenerateCommandH\x00\x12+\n\x06render\x18\x0f \x01(\x0b\x32\x19.dsl2vql.v1.RenderCommandH\x00\x12-\n\x07\x63ompile\x18\x10 \x01(\x0b\x32\x1a.dsl2vql.v1.CompileCommandH\x00\x12+\n\x06\x65xport\x18\x11 \x01(\x0b\x32\x19.dsl2vql.v1.ExportCommandH\x00\x12\x14\n\x0c\x64\x65\x66\x61ult_file\x18\x14 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x15 \x01(\tB\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dsl2vql.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYCOMMAND']._serialized_start=40
  _globals['_QUERYCOMMAND']._serialized_end=100
  _globals['_VALIDATECOMMAND']._serialized_start=102
  _globals['_VALIDATECOMMAND']._serialized_end=133
  _globals['_RESOLVECOMMAND']._serialized_start=135
  _globals['_RESOLVECOMMAND']._serialized_end=179
  _globals['_PATCHCOMMAND']._serialized_start=181
  _globals['_PATCHCOMMAND']._serialized_end=244
  _globals['_GENERATECOMMAND']._serialized_start=246
  _globals['_GENERATECOMMAND']._serialized_end=290
  _globals['_RENDERCOMMAND']._serialized_start=292
  _globals['_RENDERCOMMAND']._serialized_end=350
  _globals['_COMPILECOMMAND']._serialized_start=352
  _globals['_COMPILECOMMAND']._serialized_end=413
  _globals['_EXPORTCOMMAND']._serialized_start=415
  _globals['_EXPORTCOMMAND']._serialized_end=473
  _globals['_DSLENVELOPE']._serialized_start=476
  _globals['_DSLENVELOPE']._serialized_end=925
# @@protoc_insertion_point(module_scope)
